# Generated by Django 5.0.6 on 2024-07-08 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='isBestseller',
            field=models.BooleanField(default=False),
        ),
    ]
