# Generated by Django 5.0.6 on 2024-07-20 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_brand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='brand',
        ),
    ]
