# Generated by Django 5.0.6 on 2024-07-20 07:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_shirt_brand'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=30)),
                ('zipcode', models.SmallIntegerField(max_length=10)),
                ('city', models.CharField(max_length=30)),
                ('country', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='brand',
            name='address',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='products.address'),
        ),
    ]
