# Generated by Django 5.0.6 on 2024-07-20 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Shirt',
        ),
    ]
