# Generated by Django 5.0.6 on 2024-08-14 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='zipcode',
            field=models.SmallIntegerField(),
        ),
    ]
