# Generated by Django 4.0 on 2024-09-29 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_alter_address_zipcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(to='products.Category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='suggestions',
            field=models.ManyToManyField(to='products.Product'),
        ),
    ]
